version: "3.5"

services:
    front.web:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5100
        build:
            context: .
            dockerfile: Presentations/microCommerce.Web/Dockerfile
        depends_on:
            - customer.api
            - media.api
        ports:
            - "5100:5100"
    admin.web:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5200
        build:
            context: .
            dockerfile: Presentations/microCommerce.Admin/Dockerfile
        depends_on:
            - customer.api
            - media.api
        ports:
            - "5200:5200"

    basket.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5300
        build:
            context: .
            dockerfile: Services/microCommerce.BasketApi/Dockerfile
        ports:
            - "5300:5300"
 
    category.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5301
        build:
            context: .
            dockerfile: Services/microCommerce.CategoryApi/Dockerfile
        ports:
            - "5301:5301"
 
    checkout.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5302
        build:
            context: .
            dockerfile: Services/microCommerce.CheckoutApi/Dockerfile
        ports:
            - "5302:5302"

    customer.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5303
        build:
            context: .
            dockerfile: Services/microCommerce.CustomerApi/Dockerfile
        ports:
            - "5303:5303"

    directory.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5304
        build:
            context: .
            dockerfile: Services/microCommerce.DirectoryApi/Dockerfile
        ports:
            - "5304:5304"

    geolocation.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5304
        build:
            context: .
            dockerfile: Services/microCommerce.GeloLocationApi/Dockerfile
        ports:
            - "5304:5304"

    media.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5305
        build:
            context: .
            dockerfile: Services/microCommerce.MediaApi/Dockerfile
        ports:
            - "5305:5305"

    order.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5306
        build:
            context: .
            dockerfile: Services/microCommerce.OrderApi/Dockerfile
        ports:
            - "5306:5306"

    product.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5307
        build:
            context: .
            dockerfile: Services/microCommerce.ProductApi/Dockerfile
        ports:
            - "5307:5307"
            
    shipping.api:
        environment:
            - ASPNETCORE_ENVIRONMENT=Development
            - ASPNETCORE_URLS=http://*:5307
        build:
            context: .
            dockerfile: Services/microCommerce.ShippingApi/Dockerfile
        ports:
            - "5307:5307"